/* empty css                      */import{a as q,i as p,S as P}from"./assets/vendor-BzajH6aU.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();let n=1,h=15;function $(){n+=1}function H(){n=1}async function y(t){const o="46450573-9b5e41256c0ad0f1dd9121c30",r=new URLSearchParams({key:o,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:h});return(await q.get(`https://pixabay.com/api/?${r}`)).data}const v=document.querySelector(".wrapp"),u=document.querySelector(".list");function L(t,o){if(t.total===0){u.innerHTML="";return}else{let r=Math.ceil(t.totalHits/h);console.log(r),r===n&&(l(),p.error({message:"We're sorry, but you've reached the end of search results.",messageSize:18,messageLineHeight:30,position:"topRight"})),w();const i=t.hits.map(e=>`<li class="list-item"><a href="${e.largeImageURL}" data-source="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
          <div class="wrapp-items">
          <div class="info-item"><p class="bold">Likes</p>
          <p>${e.likes}</p>
          </div>
          <div class="info-item"><p class="bold">Views</p>
          <p>${e.views}</p>
          </div>
          <div class="info-item"><p class="bold">Comments</p>
          <p>${e.comments}</p>
          </div>
          <div class="info-item"><p class="bold">Downloads</p>
          <p>${e.downloads}</p>
          </div>

          </div></li>`).join("");return n!==1?u.insertAdjacentHTML("beforeend",i):u.innerHTML=i,o.refresh(),!0}}function b(){v.style.display="block"}function w(){v.style.display="none"}document.querySelector("body");let S=new P(".list a",{captions:!0,captionsData:"alt",captionDelay:250,loop:!0});const I=document.querySelector(".form"),f=document.querySelector(".user-input"),c=document.querySelector(".test1");function R(){c.style.display="block",console.log("Button shown")}function l(){c.style.display="none",console.log("Button hidden")}l();let a;I.addEventListener("submit",async t=>{if(t.preventDefault(),f.value.trim()?(a=f.value.trim(),H(),c.removeEventListener("click",g)):a=void 0,a){b();try{const o=await y(a);if(L(o,S))R(),c.addEventListener("click",g);else throw new Error("No images found!")}catch{l(),p.error({message:"Sorry, there are no images matching your search query. Please try again!",messageSize:18,messageLineHeight:30,position:"topRight"})}finally{w()}}});async function g(){$(),console.log("Current page:",n);try{b();const t=await y(a);if(t.hits.length===0){l(),p.warning({message:"No more images to load.",messageSize:18,messageLineHeight:30,position:"topRight"});return}L(t,S),setTimeout(()=>{window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})},300),m()}catch(t){console.log(t)}}function m(){const o=document.querySelector(".list").getBoundingClientRect();o.height&&o.height}document.addEventListener("scroll",m);m();
//# sourceMappingURL=index.js.map
