/* empty css                      */import{a as P,i as l,S as q}from"./assets/vendor-BzajH6aU.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();let a=1,h=15;function H(){a+=1}function R(){a=1}async function y(t){const o="46450573-9b5e41256c0ad0f1dd9121c30",i=new URLSearchParams({key:o,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:h});return(await P.get(`https://pixabay.com/api/?${i}`)).data}const w=document.querySelector(".wrapp"),p=document.querySelector(".list");function v(t,o){if(t.total===0){p.innerHTML="";return}else{let i=Math.ceil(t.totalHits/h);console.log(i),i===a&&(d(),l.error({message:"We're sorry, but you've reached the end of search results.",messageSize:18,messageLineHeight:30,position:"topRight"})),m();const r=t.hits.map(e=>`<li class="list-item"><a href="${e.largeImageURL}" data-source="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
          <div class="wrapp-items">
          <div class="info-item"><p class="bold">Likes</p>
          <p>${e.likes}</p>
          </div>
          <div class="info-item"><p class="bold">Views</p>
          <p>${e.views}</p>
          </div>
          <div class="info-item"><p class="bold">Comments</p>
          <p>${e.comments}</p>
          </div>
          <div class="info-item"><p class="bold">Downloads</p>
          <p>${e.downloads}</p>
          </div>

          </div></li>`).join("");return a!==1?p.insertAdjacentHTML("beforeend",r):p.innerHTML=r,o.refresh(),!0}}function L(){w.style.display="block"}function m(){w.style.display="none"}document.querySelector("body");let b=new q(".list a",{captions:!0,captionsData:"alt",captionDelay:250,loop:!0});const $=document.querySelector(".form"),g=document.querySelector(".user-input"),c=document.querySelector(".test1");function S(){c.style.display="block"}function d(){c.style.display="none"}d();let n;$.addEventListener("submit",async t=>{if(t.preventDefault(),g.value.trim()?(n=g.value.trim(),R(),c.removeEventListener("click",f)):n=void 0,n){L();try{const o=await y(n);if(v(o,b))S(),c.addEventListener("click",f);else throw new Error("No images found!")}catch{l.error({title:"Error",message:"Oops, something went wrong. Please try again later.",messageSize:18,messageLineHeight:30,position:"topRight"})}finally{m()}}});async function f(){H();try{L();const t=await y(n);if(t.hits.length===0){d(),l.warning({message:"No more images to load.",messageSize:18,messageLineHeight:30,position:"topRight"});return}v(t,b),t.hits.length<15?d():S(),window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"}),I()}catch{l.error({title:"Error",message:"Oops, something went wrong. Please try again later.",messageSize:18,messageLineHeight:30,position:"topRight"})}finally{m()}}function I(){const o=document.querySelector(".list").getBoundingClientRect();o.height&&o.height}
//# sourceMappingURL=index.js.map
